// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PictureScan.Models;

namespace PictureScan.DBMigrator.Migrations
{
    [DbContext(typeof(PSContext))]
    [Migration("20191114205639_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PictureScan.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CenterBottom")
                        .HasColumnType("bigint");

                    b.Property<long>("CenterCenter")
                        .HasColumnType("bigint");

                    b.Property<long>("CenterTop")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationFileDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileDirectory")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("varchar(26)");

                    b.Property<long>("LeftBottom")
                        .HasColumnType("bigint");

                    b.Property<long>("LeftCenter")
                        .HasColumnType("bigint");

                    b.Property<long>("LeftTop")
                        .HasColumnType("bigint");

                    b.Property<long>("RightBottom")
                        .HasColumnType("bigint");

                    b.Property<long>("RightCenter")
                        .HasColumnType("bigint");

                    b.Property<long>("RightTop")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Picture");
                });
#pragma warning restore 612, 618
        }
    }
}
